<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="RJCJ IT About Page">
  <meta name="keywords" content="RJCJ IT, About, Application, Opportunities, Home">
  <meta name="author" content="JG, RS, JP, CM">
  <title>About Our Group</title>
  <link rel="stylesheet" type="text/css" href="styles/styles.css"/>
  <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet"/>
</head>
    <div>
      <figure id="image1">
        <a href="images/rjcj.png">
          <img src="images/rjcj.png" alt="RJCJ logo" title="filesize 232kb" style="width:100px; height:auto;">
        </a>
      </figure>
    </div>
    <h1 style="margin: 0;">About Our Group</h1>
    <p style="margin-top: 0.5em;">
      <em>Class Time:</em> Monday 10:00 AM – 12:30 PM | <em>Tutor:</em> Razeen Hashmi
    </p>