<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <meta name="description" content="RJCJ IT About Page">
  <meta name="keywords" content="RJCJ IT, About, Application, Opportunities, Home">
  <meta name="author" content="JG, RS, JP, CM">
  <title>About Our Group</title>
  <link rel="stylesheet" type="text/css" href="styles/styles.css"/>
</head>

