<div id="header">
    <header>
        <nav>
            <ul class="nav-menu">
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Job Descriptions</a></li>
                <li><a href="apply.php">Apply Now</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="login.php">Manager Login</a></li>
                <li><a href="mailto:info@rjcj.com.au">Contact Us</a></li>
            </ul>
        </nav>
        <figure class="logo">
            <a href="styles/images/rjcj.png">
              <img src="styles/images/rjcj.png" alt="RJCJ logo" title="filesize 232kb">
            </a>
        </figure>
        <hr>
    </header>
</div>