<div id="header">
    <header>
        <div>
            <figure id="image1">
                <a href="images/rjcj.png">
                    <img src="images/rjcj.png" alt="RJCJ logo" title="filesize 232kb" style="width:100px; height:auto;">
                </a>
            </figure>
        </div>
        <h1>RJCJ IT</h1>
        <nav>
            <ul class="nav-menu">
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Job Descriptions</a></li>
                <li><a href="apply.php">Apply Now</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="mailto:info@rjcj.com.au">Contact Us</a></li>
            </ul>
        </nav>
        <hr>
    </header>
</div>